import type { WeaponCategory, WeaponDef } from './types';
import { models } from './models';

/** All 46 weapons. Price 0 = unlocked from the start. */
export const WEAPONS: WeaponDef[] = [
  // ---------------- Blunt ----------------
  {
    id: 'fists',
    name: 'Fists',
    category: 'blunt',
    archetype: 'melee',
    icon: '🥊',
    price: 0,
    damage: 9,
    type: 'blunt',
    impulse: 28,
    cooldown: 0.12,
    auto: true,
    sound: 'whoosh',
    hitSound: 'punch',
    model: models.glove,
    opts: { swing: 'jab', reach: 0.12 },
  },
  {
    id: 'bat',
    name: 'Baseball Bat',
    category: 'blunt',
    archetype: 'melee',
    icon: '🏏',
    price: 0,
    damage: 17,
    type: 'blunt',
    impulse: 70,
    cooldown: 0.3,
    auto: true,
    sound: 'whoosh',
    hitSound: 'thunk',
    words: ['CRACK!', 'HOME RUN!', 'THWACK!'],
    model: models.bat,
    opts: { swing: 'side', reach: 0.72 },
  },
  {
    id: 'pan',
    name: 'Frying Pan',
    category: 'blunt',
    archetype: 'melee',
    icon: '🍳',
    price: 150,
    damage: 14,
    type: 'blunt',
    impulse: 50,
    cooldown: 0.25,
    auto: true,
    sound: 'whoosh',
    hitSound: 'clang',
    words: ['BONG!', 'CLANG!', 'DONG!'],
    model: models.pan,
    opts: { swing: 'side', reach: 0.42 },
  },
  {
    id: 'sledgehammer',
    name: 'Sledgehammer',
    category: 'blunt',
    archetype: 'melee',
    icon: '🔨',
    price: 800,
    damage: 34,
    type: 'blunt',
    impulse: 150,
    cooldown: 0.6,
    auto: true,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['CRUNCH!', 'KA-THUNK!', 'SMASH!'],
    model: models.sledgehammer,
    opts: { swing: 'overhead', reach: 0.74 },
  },
  {
    id: 'brick',
    name: 'Brick',
    category: 'blunt',
    archetype: 'thrown',
    icon: '🧱',
    price: 0,
    damage: 20,
    type: 'blunt',
    impulse: 0,
    cooldown: 0.25,
    auto: true,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['BONK!', 'THUD!'],
    model: models.brick,
    opts: { speed: 14, mass: 2.5, shape: 'box', half: [0.1, 0.033, 0.05] },
  },
  {
    id: 'keyboard',
    name: 'Keyboard',
    category: 'blunt',
    archetype: 'melee',
    icon: '⌨️',
    price: 300,
    damage: 12,
    type: 'blunt',
    impulse: 45,
    cooldown: 0.22,
    auto: true,
    sound: 'whoosh',
    hitSound: 'slap',
    words: ['CTRL+ALT+DEL!', 'CLACK!', 'ESC!', 'ALT+F4!'],
    model: models.keyboard,
    opts: { swing: 'overhead', reach: 0.5 },
  },
  {
    id: 'chicken',
    name: 'Rubber Chicken',
    category: 'blunt',
    archetype: 'melee',
    icon: '🐔',
    price: 200,
    damage: 5,
    type: 'blunt',
    impulse: 40,
    cooldown: 0.15,
    auto: true,
    sound: 'whoosh',
    hitSound: 'squeak',
    words: ['BAWK!', 'SQUEAK!', 'HONK!'],
    model: models.chicken,
    opts: { swing: 'side', reach: 0.55 },
  },

  // ---------------- Sharp ----------------
  {
    id: 'katana',
    name: 'Katana',
    category: 'sharp',
    archetype: 'melee',
    icon: '🗡️',
    price: 1200,
    damage: 26,
    type: 'sharp',
    impulse: 30,
    cooldown: 0.28,
    auto: true,
    sound: 'whoosh',
    hitSound: 'slice',
    words: ['SLASH!', 'SHING!', 'SLICE!'],
    model: models.katana,
    opts: { swing: 'side', reach: 0.9 },
  },
  {
    id: 'axe',
    name: 'Fire Axe',
    category: 'sharp',
    archetype: 'melee',
    icon: '🪓',
    price: 950,
    damage: 34,
    type: 'sharp',
    impulse: 60,
    cooldown: 0.5,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['CHOP!', 'THWACK!', 'TIMBER!'],
    model: models.axe,
    opts: { swing: 'overhead', reach: 0.66 },
  },
  {
    id: 'cleaver',
    name: 'Meat Cleaver',
    category: 'sharp',
    archetype: 'projectile',
    icon: '🔪',
    price: 700,
    damage: 24,
    type: 'sharp',
    impulse: 20,
    cooldown: 0.35,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['THUNK!', 'CHOP!'],
    model: models.cleaver,
    opts: { speed: 14, spin: 22, gravity: 0.6 },
  },
  {
    id: 'chainsaw',
    name: 'Chainsaw',
    category: 'sharp',
    archetype: 'saw',
    icon: '⚙️',
    price: 3000,
    damage: 4.5,
    type: 'sharp',
    impulse: 4,
    cooldown: 0,
    sound: 'whoosh',
    loop: 'chainsaw',
    model: models.chainsaw,
  },
  {
    id: 'knives',
    name: 'Throwing Knives',
    category: 'sharp',
    archetype: 'projectile',
    icon: '🗡',
    price: 600,
    damage: 11,
    type: 'sharp',
    impulse: 8,
    cooldown: 0.3,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['THWIP!', 'SHNK!'],
    model: models.knife,
    opts: { speed: 18, spin: 30, gravity: 0.4, count: 3 },
  },

  // ---------------- Guns ----------------
  {
    id: 'pistol',
    name: 'Pistol',
    category: 'gun',
    archetype: 'hitscan',
    icon: '🔫',
    price: 0,
    damage: 15,
    type: 'pierce',
    impulse: 22,
    cooldown: 0.22,
    auto: true,
    sound: 'gunshot',
    hitSound: 'stab',
    words: ['BANG!', 'POP!'],
    model: models.pistol,
  },
  {
    id: 'shotgun',
    name: 'Shotgun',
    category: 'gun',
    archetype: 'hitscan',
    icon: '💥',
    price: 1600,
    damage: 7,
    type: 'pierce',
    impulse: 14,
    cooldown: 0.85,
    auto: true,
    sound: 'shotgun',
    hitSound: 'splat',
    words: ['BLAM!', 'KA-BLAM!'],
    model: models.shotgun,
    opts: { pellets: 9, spread: 0.05 },
  },
  {
    id: 'nailgun',
    name: 'Nail Gun',
    category: 'gun',
    archetype: 'projectile',
    icon: '📌',
    price: 1400,
    damage: 5,
    type: 'pierce',
    impulse: 6,
    cooldown: 0.08,
    auto: true,
    sound: 'thunk',
    hitSound: 'stab',
    words: ['CHUNK!', 'TAK!'],
    model: models.nailgun,
    projectile: models.nail,
    opts: { speed: 45, gravity: 0.05 },
  },
  {
    id: 'crossbow',
    name: 'Crossbow',
    category: 'gun',
    archetype: 'projectile',
    icon: '🏹',
    price: 1800,
    damage: 38,
    type: 'pierce',
    impulse: 95,
    cooldown: 0.7,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['THWACK!', 'BULLSEYE!'],
    model: models.crossbow,
    projectile: models.bolt,
    opts: { speed: 40, gravity: 0.1 },
  },

  // ---------------- Explosive ----------------
  {
    id: 'grenade',
    name: 'Grenade',
    category: 'explosive',
    archetype: 'thrown',
    icon: '💣',
    price: 2000,
    damage: 85,
    type: 'explosive',
    impulse: 0,
    cooldown: 0.6,
    sound: 'whoosh',
    hitSound: 'thunk',
    model: models.grenade,
    opts: { speed: 11, mass: 0.6, fuse: 1.8, radius: 2.2, shape: 'ball', half: [0.07, 0.07, 0.07] },
  },
  {
    id: 'dynamite',
    name: 'Sticky Dynamite',
    category: 'explosive',
    archetype: 'thrown',
    icon: '🧨',
    price: 2500,
    damage: 90,
    type: 'explosive',
    impulse: 0,
    cooldown: 0.7,
    sound: 'whoosh',
    hitSound: 'thunk',
    model: models.dynamite,
    opts: { speed: 11, mass: 0.8, fuse: 2.6, radius: 2.4, sticky: true, shape: 'box', half: [0.06, 0.1, 0.05] },
  },
  {
    id: 'rocket',
    name: 'Rocket Launcher',
    category: 'explosive',
    archetype: 'projectile',
    icon: '🚀',
    price: 4500,
    damage: 105,
    type: 'explosive',
    impulse: 0,
    cooldown: 1.1,
    sound: 'whoosh',
    model: models.rocketLauncher,
    projectile: models.rocket,
    opts: { speed: 16, gravity: 0, radius: 2.4, embed: false },
  },

  // ---------------- Elemental ----------------
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    category: 'elemental',
    archetype: 'spray',
    icon: '🔥',
    price: 3500,
    damage: 3,
    type: 'fire',
    impulse: 0.5,
    cooldown: 0,
    sound: 'ignite',
    loop: 'flame',
    model: models.flamethrower,
    opts: { range: 4.5 },
  },
  {
    id: 'taser',
    name: 'Taser',
    category: 'elemental',
    archetype: 'spray',
    icon: '⚡',
    price: 2400,
    damage: 2.4,
    type: 'electric',
    impulse: 1,
    cooldown: 0,
    sound: 'zap',
    loop: 'electric',
    model: models.taser,
    opts: { range: 7 },
  },
  {
    id: 'freezeray',
    name: 'Freeze Ray',
    category: 'elemental',
    archetype: 'spray',
    icon: '❄️',
    price: 3000,
    damage: 2,
    type: 'cold',
    impulse: 0.3,
    cooldown: 0,
    sound: 'freeze',
    loop: 'freezeRay',
    model: models.freezeRay,
    opts: { range: 9 },
  },

  // ---------------- Drop ----------------
  {
    id: 'anvil',
    name: 'Anvil',
    category: 'drop',
    archetype: 'thrown',
    icon: '⚓',
    price: 4000,
    damage: 90,
    type: 'blunt',
    impulse: 0,
    cooldown: 1.2,
    sound: 'whoosh',
    hitSound: 'clang',
    words: ['CLANG!', 'SPLAT!', 'BONK!'],
    model: models.anvil,
    opts: { drop: true, mass: 90, shape: 'box', half: [0.25, 0.19, 0.11] },
  },
  {
    id: 'bowling',
    name: 'Bowling Ball',
    category: 'drop',
    archetype: 'thrown',
    icon: '🎳',
    price: 1000,
    damage: 30,
    type: 'blunt',
    impulse: 0,
    cooldown: 0.5,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['STRIKE!', 'BONK!'],
    model: models.bowlingBall,
    opts: { drop: true, mass: 7, shape: 'ball', half: [0.11, 0.11, 0.11] },
  },

  // ================================================================ v2 arsenal
  // ---------------- Magic ----------------
  {
    id: 'blackhole',
    name: 'Black Hole',
    category: 'magic',
    archetype: 'field',
    icon: '🕳️',
    price: 6000,
    damage: 7,
    type: 'sharp',
    impulse: 0,
    cooldown: 7,
    sound: 'plasma',
    loop: 'vortex',
    words: ['SPAGHETTI!', 'SLURP!'],
    model: models.blackHoleOrb,
    opts: { kind: 'blackhole', duration: 5 },
  },
  {
    id: 'tornado',
    name: 'Tornado',
    category: 'magic',
    archetype: 'field',
    icon: '🌪️',
    price: 4500,
    damage: 3,
    type: 'blunt',
    impulse: 0,
    cooldown: 7.5,
    sound: 'whoosh',
    loop: 'wind',
    model: models.tornadoJar,
    opts: { kind: 'tornado', duration: 6 },
  },
  {
    id: 'swords',
    name: 'Flying Swords',
    category: 'magic',
    archetype: 'summon',
    icon: '⚔️',
    price: 5000,
    damage: 16,
    type: 'sharp',
    impulse: 8,
    cooldown: 8.5,
    sound: 'sword',
    hitSound: 'slice',
    words: ['SHING!', 'SLASH!', 'EN GARDE!'],
    model: models.swordHilt,
    projectile: models.spectralSword,
    opts: { kind: 'swords', count: 5, duration: 8 },
  },
  {
    id: 'bees',
    name: 'Bee Swarm',
    category: 'magic',
    archetype: 'summon',
    icon: '🐝',
    price: 2200,
    damage: 1.5,
    type: 'pierce',
    impulse: 0.5,
    cooldown: 8,
    sound: 'pop',
    hitSound: 'squeak',
    loop: 'bees',
    words: ['BZZ!', 'STING!', 'OUCH!'],
    model: models.beeHive,
    projectile: models.bee,
    opts: { kind: 'bees', count: 14, duration: 7 },
  },
  {
    id: 'lightning',
    name: 'Lightning Strike',
    category: 'magic',
    archetype: 'strike',
    icon: '🌩️',
    price: 3800,
    damage: 45,
    type: 'electric',
    impulse: 20,
    cooldown: 1.2,
    sound: 'thunder',
    hitSound: 'zap',
    words: ['KRAKOOM!', 'ZZZAP!', 'SMITE!'],
    model: () => models.staff(0x9be7ff),
    opts: { kind: 'lightning' },
  },
  {
    id: 'icespikes',
    name: 'Ice Spikes',
    category: 'magic',
    archetype: 'strike',
    icon: '🧊',
    price: 3200,
    damage: 30,
    type: 'pierce',
    impulse: 0,
    cooldown: 1.4,
    sound: 'spikes',
    hitSound: 'stab',
    words: ['SKEWERED!', 'CRUNCH!', 'BRRR!'],
    model: () => models.staff(0xbfefff),
    opts: { kind: 'icespikes' },
  },
  {
    id: 'meteor',
    name: 'Meteor Shower',
    category: 'magic',
    archetype: 'strike',
    icon: '☄️',
    price: 5500,
    damage: 40,
    type: 'explosive',
    impulse: 0,
    cooldown: 3.5,
    sound: 'meteor',
    model: () => models.remote(0xff6b35),
    opts: { kind: 'meteor', count: 5, radius: 1.5 },
  },
  {
    id: 'tesla',
    name: 'Tesla Coil',
    category: 'magic',
    archetype: 'turret',
    icon: '🗼',
    price: 4200,
    damage: 9,
    type: 'electric',
    impulse: 6,
    cooldown: 2,
    sound: 'zap',
    hitSound: 'zap',
    loop: 'tesla',
    model: models.teslaDevice,
    opts: { duration: 12 },
  },

  // ---------------- Brutal ----------------
  {
    id: 'laser',
    name: 'Laser Cutter',
    category: 'sharp',
    archetype: 'spray',
    icon: '🔴',
    price: 5200,
    damage: 4,
    type: 'sharp',
    impulse: 0.5,
    cooldown: 0,
    sound: 'zap',
    hitSound: 'slice',
    loop: 'laser',
    words: ['SIZZLE!', 'SLICE!', 'VWORP!'],
    model: models.laserCutter,
    opts: { range: 9, beam: 0xff1744 },
  },
  {
    id: 'minigun',
    name: 'Minigun',
    category: 'gun',
    archetype: 'hitscan',
    icon: '🌀',
    price: 5800,
    damage: 7,
    type: 'pierce',
    impulse: 6,
    cooldown: 0.05,
    auto: true,
    sound: 'gunshot',
    loop: 'minigun',
    words: ['BRRRRT!', 'RATATAT!'],
    model: models.minigun,
    opts: { spread: 0.02, spinUp: 0.4 },
  },
  {
    id: 'buzzsaw',
    name: 'Buzzsaw Launcher',
    category: 'sharp',
    archetype: 'projectile',
    icon: '💿',
    price: 3600,
    damage: 28,
    type: 'sharp',
    impulse: 10,
    cooldown: 0.7,
    sound: 'sword',
    hitSound: 'slice',
    words: ['BZZZT!', 'RIP!', 'SHRED!'],
    model: models.buzzsawLauncher,
    projectile: models.sawDisc,
    opts: { speed: 22, gravity: 0, spin: 40, spinAxis: 'y', ricochet: 3, embed: false },
  },
  {
    id: 'guillotine',
    name: 'Guillotine',
    category: 'sharp',
    archetype: 'strike',
    icon: '🏛️',
    price: 6000,
    damage: 220,
    type: 'sharp',
    impulse: 5,
    cooldown: 3,
    sound: 'guillotine',
    hitSound: 'slice',
    words: ['OFF WITH HIS HEAD!', 'CHOP!'],
    model: () => models.remote(0x6b4a33),
    opts: { kind: 'guillotine' },
  },
  {
    id: 'banhammer',
    name: 'Ban Hammer',
    category: 'blunt',
    archetype: 'melee',
    icon: '🚫',
    price: 4800,
    damage: 45,
    type: 'blunt',
    impulse: 160,
    cooldown: 1.1,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['BANNED!', 'PERMABAN!', 'KICKED!'],
    model: models.banHammer,
    opts: { swing: 'overhead', reach: 1.2, shockwave: 2.4 },
  },
  {
    id: 'wreckingball',
    name: 'Wrecking Ball',
    category: 'drop',
    archetype: 'thrown',
    icon: '⚫',
    price: 5000,
    damage: 80,
    type: 'blunt',
    impulse: 0,
    cooldown: 2.5,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['WRECKED!', 'KA-THUNK!', 'DEMOLISHED!'],
    model: models.wreckingBall,
    opts: { pendulum: true, mass: 400, shape: 'ball', half: [0.45, 0.45, 0.45], speed: 7 },
  },
  {
    id: 'piano',
    name: 'Piano',
    category: 'drop',
    archetype: 'thrown',
    icon: '🎹',
    price: 4500,
    damage: 110,
    type: 'blunt',
    impulse: 0,
    cooldown: 2,
    sound: 'whoosh',
    hitSound: 'piano',
    words: ['PLONK!', 'FORTISSIMO!', 'CRASH!'],
    model: models.piano,
    opts: { drop: true, mass: 250, shape: 'box', half: [0.7, 0.65, 0.4], landSound: 'piano' },
  },

  // ---------------- Gadgets ----------------
  {
    id: 'web',
    name: 'Web Shooter',
    category: 'special',
    archetype: 'tether',
    icon: '🕸️',
    price: 2500,
    damage: 2,
    type: 'blunt',
    impulse: 3,
    cooldown: 0.35,
    sound: 'web',
    hitSound: 'slap',
    words: ['THWIP!', 'STUCK!'],
    model: models.webShooter,
    opts: { kind: 'web', duration: 10 },
  },
  {
    id: 'harpoon',
    name: 'Harpoon Gun',
    category: 'special',
    archetype: 'tether',
    icon: '🔱',
    price: 4000,
    damage: 30,
    type: 'pierce',
    impulse: 25,
    cooldown: 1.2,
    sound: 'harpoon',
    hitSound: 'stab',
    words: ['SKEWER!', 'THWUNK!', 'GOTCHA!'],
    model: models.harpoonGun,
    opts: { kind: 'harpoon', duration: 12 },
  },
  {
    id: 'gravitygun',
    name: 'Gravity Gun',
    category: 'special',
    archetype: 'gravity',
    icon: '🌌',
    price: 5500,
    damage: 5,
    type: 'blunt',
    impulse: 0,
    cooldown: 0.4,
    sound: 'plasma',
    loop: 'gravity',
    model: models.gravityGun,
  },
  {
    id: 'magnet',
    name: 'Magnet',
    category: 'special',
    archetype: 'field',
    icon: '🧲',
    price: 2800,
    damage: 11,
    type: 'blunt',
    impulse: 0,
    cooldown: 5,
    sound: 'clang',
    hitSound: 'clang',
    loop: 'gravity',
    model: models.magnet,
    opts: { kind: 'magnet', duration: 4.5 },
  },
  {
    id: 'plasma',
    name: 'Plasma Rifle',
    category: 'gun',
    archetype: 'projectile',
    icon: '🟢',
    price: 4000,
    damage: 25,
    type: 'explosive',
    impulse: 0,
    cooldown: 0.35,
    auto: true,
    sound: 'plasma',
    model: models.plasmaRifle,
    projectile: models.plasmaBolt,
    opts: { speed: 28, gravity: 0, radius: 1, trail: 0x39ff88 },
  },
  {
    id: 'shuriken',
    name: 'Shuriken',
    category: 'sharp',
    archetype: 'projectile',
    icon: '✴️',
    price: 1800,
    damage: 12,
    type: 'sharp',
    impulse: 4,
    cooldown: 0.45,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['SHINK!', 'HI-YAH!'],
    model: models.shuriken,
    opts: { speed: 24, gravity: 0.1, count: 3, spin: 30, spinAxis: 'y' },
  },
  {
    id: 'boomerang',
    name: 'Boomerang',
    category: 'blunt',
    archetype: 'projectile',
    icon: '🪃',
    price: 1500,
    damage: 16,
    type: 'blunt',
    impulse: 20,
    cooldown: 0.9,
    sound: 'whoosh',
    hitSound: 'thunk',
    words: ['BONK!', 'WHAP!', "G'DAY!"],
    model: models.boomerang,
    opts: { speed: 14, gravity: 0, spin: 22, spinAxis: 'y', returns: true },
  },
];

export const CATEGORIES: Array<{ id: WeaponCategory | 'all'; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'blunt', label: 'Blunt' },
  { id: 'sharp', label: 'Sharp' },
  { id: 'gun', label: 'Guns' },
  { id: 'explosive', label: 'Boom' },
  { id: 'elemental', label: 'Elemental' },
  { id: 'magic', label: 'Magic' },
  { id: 'drop', label: 'Drop' },
  { id: 'special', label: 'Gadgets' },
];

export function weaponById(id: string): WeaponDef {
  const w = WEAPONS.find((d) => d.id === id);
  if (!w) throw new Error(`Unknown weapon ${id}`);
  return w;
}
