import type { WeaponCategory, WeaponDef } from './types';
import { models } from './models';

/** All 24 weapons. Price 0 = unlocked from the start. */
export const WEAPONS: WeaponDef[] = [
  // ---------------- Blunt ----------------
  {
    id: 'fists',
    name: 'Fists',
    category: 'blunt',
    archetype: 'melee',
    icon: '🥊',
    price: 0,
    damage: 9,
    type: 'blunt',
    impulse: 28,
    cooldown: 0.12,
    auto: true,
    sound: 'whoosh',
    hitSound: 'punch',
    model: models.glove,
    opts: { swing: 'jab', reach: 0.12 },
  },
  {
    id: 'bat',
    name: 'Baseball Bat',
    category: 'blunt',
    archetype: 'melee',
    icon: '🏏',
    price: 0,
    damage: 17,
    type: 'blunt',
    impulse: 70,
    cooldown: 0.3,
    auto: true,
    sound: 'whoosh',
    hitSound: 'thunk',
    words: ['CRACK!', 'HOME RUN!', 'THWACK!'],
    model: models.bat,
    opts: { swing: 'side', reach: 0.72 },
  },
  {
    id: 'pan',
    name: 'Frying Pan',
    category: 'blunt',
    archetype: 'melee',
    icon: '🍳',
    price: 150,
    damage: 14,
    type: 'blunt',
    impulse: 50,
    cooldown: 0.25,
    auto: true,
    sound: 'whoosh',
    hitSound: 'clang',
    words: ['BONG!', 'CLANG!', 'DONG!'],
    model: models.pan,
    opts: { swing: 'side', reach: 0.42 },
  },
  {
    id: 'sledgehammer',
    name: 'Sledgehammer',
    category: 'blunt',
    archetype: 'melee',
    icon: '🔨',
    price: 800,
    damage: 34,
    type: 'blunt',
    impulse: 150,
    cooldown: 0.6,
    auto: true,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['CRUNCH!', 'KA-THUNK!', 'SMASH!'],
    model: models.sledgehammer,
    opts: { swing: 'overhead', reach: 0.74 },
  },
  {
    id: 'brick',
    name: 'Brick',
    category: 'blunt',
    archetype: 'thrown',
    icon: '🧱',
    price: 0,
    damage: 20,
    type: 'blunt',
    impulse: 0,
    cooldown: 0.25,
    auto: true,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['BONK!', 'THUD!'],
    model: models.brick,
    opts: { speed: 14, mass: 2.5, shape: 'box', half: [0.1, 0.033, 0.05] },
  },
  {
    id: 'keyboard',
    name: 'Keyboard',
    category: 'blunt',
    archetype: 'melee',
    icon: '⌨️',
    price: 300,
    damage: 12,
    type: 'blunt',
    impulse: 45,
    cooldown: 0.22,
    auto: true,
    sound: 'whoosh',
    hitSound: 'slap',
    words: ['CTRL+ALT+DEL!', 'CLACK!', 'ESC!', 'ALT+F4!'],
    model: models.keyboard,
    opts: { swing: 'overhead', reach: 0.5 },
  },
  {
    id: 'chicken',
    name: 'Rubber Chicken',
    category: 'blunt',
    archetype: 'melee',
    icon: '🐔',
    price: 200,
    damage: 5,
    type: 'blunt',
    impulse: 40,
    cooldown: 0.15,
    auto: true,
    sound: 'whoosh',
    hitSound: 'squeak',
    words: ['BAWK!', 'SQUEAK!', 'HONK!'],
    model: models.chicken,
    opts: { swing: 'side', reach: 0.55 },
  },

  // ---------------- Sharp ----------------
  {
    id: 'katana',
    name: 'Katana',
    category: 'sharp',
    archetype: 'melee',
    icon: '🗡️',
    price: 1200,
    damage: 26,
    type: 'sharp',
    impulse: 30,
    cooldown: 0.28,
    auto: true,
    sound: 'whoosh',
    hitSound: 'slice',
    words: ['SLASH!', 'SHING!', 'SLICE!'],
    model: models.katana,
    opts: { swing: 'side', reach: 0.9 },
  },
  {
    id: 'axe',
    name: 'Fire Axe',
    category: 'sharp',
    archetype: 'melee',
    icon: '🪓',
    price: 950,
    damage: 34,
    type: 'sharp',
    impulse: 60,
    cooldown: 0.5,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['CHOP!', 'THWACK!', 'TIMBER!'],
    model: models.axe,
    opts: { swing: 'overhead', reach: 0.66 },
  },
  {
    id: 'cleaver',
    name: 'Meat Cleaver',
    category: 'sharp',
    archetype: 'projectile',
    icon: '🔪',
    price: 700,
    damage: 24,
    type: 'sharp',
    impulse: 20,
    cooldown: 0.35,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['THUNK!', 'CHOP!'],
    model: models.cleaver,
    opts: { speed: 14, spin: 22, gravity: 0.6 },
  },
  {
    id: 'chainsaw',
    name: 'Chainsaw',
    category: 'sharp',
    archetype: 'saw',
    icon: '⚙️',
    price: 3000,
    damage: 4.5,
    type: 'sharp',
    impulse: 4,
    cooldown: 0,
    sound: 'whoosh',
    loop: 'chainsaw',
    model: models.chainsaw,
  },
  {
    id: 'knives',
    name: 'Throwing Knives',
    category: 'sharp',
    archetype: 'projectile',
    icon: '🗡',
    price: 600,
    damage: 11,
    type: 'sharp',
    impulse: 8,
    cooldown: 0.3,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['THWIP!', 'SHNK!'],
    model: models.knife,
    opts: { speed: 18, spin: 30, gravity: 0.4, count: 3 },
  },

  // ---------------- Guns ----------------
  {
    id: 'pistol',
    name: 'Pistol',
    category: 'gun',
    archetype: 'hitscan',
    icon: '🔫',
    price: 0,
    damage: 15,
    type: 'pierce',
    impulse: 22,
    cooldown: 0.22,
    auto: true,
    sound: 'gunshot',
    hitSound: 'stab',
    words: ['BANG!', 'POP!'],
    model: models.pistol,
  },
  {
    id: 'shotgun',
    name: 'Shotgun',
    category: 'gun',
    archetype: 'hitscan',
    icon: '💥',
    price: 1600,
    damage: 7,
    type: 'pierce',
    impulse: 14,
    cooldown: 0.85,
    auto: true,
    sound: 'shotgun',
    hitSound: 'splat',
    words: ['BLAM!', 'KA-BLAM!'],
    model: models.shotgun,
    opts: { pellets: 9, spread: 0.05 },
  },
  {
    id: 'nailgun',
    name: 'Nail Gun',
    category: 'gun',
    archetype: 'projectile',
    icon: '📌',
    price: 1400,
    damage: 5,
    type: 'pierce',
    impulse: 6,
    cooldown: 0.08,
    auto: true,
    sound: 'thunk',
    hitSound: 'stab',
    words: ['CHUNK!', 'TAK!'],
    model: models.nailgun,
    projectile: models.nail,
    opts: { speed: 45, gravity: 0.05 },
  },
  {
    id: 'crossbow',
    name: 'Crossbow',
    category: 'gun',
    archetype: 'projectile',
    icon: '🏹',
    price: 1800,
    damage: 38,
    type: 'pierce',
    impulse: 95,
    cooldown: 0.7,
    auto: true,
    sound: 'whoosh',
    hitSound: 'stab',
    words: ['THWACK!', 'BULLSEYE!'],
    model: models.crossbow,
    projectile: models.bolt,
    opts: { speed: 40, gravity: 0.1 },
  },

  // ---------------- Explosive ----------------
  {
    id: 'grenade',
    name: 'Grenade',
    category: 'explosive',
    archetype: 'thrown',
    icon: '💣',
    price: 2000,
    damage: 85,
    type: 'explosive',
    impulse: 0,
    cooldown: 0.6,
    sound: 'whoosh',
    hitSound: 'thunk',
    model: models.grenade,
    opts: { speed: 11, mass: 0.6, fuse: 1.8, radius: 2.2, shape: 'ball', half: [0.07, 0.07, 0.07] },
  },
  {
    id: 'dynamite',
    name: 'Sticky Dynamite',
    category: 'explosive',
    archetype: 'thrown',
    icon: '🧨',
    price: 2500,
    damage: 90,
    type: 'explosive',
    impulse: 0,
    cooldown: 0.7,
    sound: 'whoosh',
    hitSound: 'thunk',
    model: models.dynamite,
    opts: { speed: 11, mass: 0.8, fuse: 2.6, radius: 2.4, sticky: true, shape: 'box', half: [0.06, 0.1, 0.05] },
  },
  {
    id: 'rocket',
    name: 'Rocket Launcher',
    category: 'explosive',
    archetype: 'projectile',
    icon: '🚀',
    price: 4500,
    damage: 105,
    type: 'explosive',
    impulse: 0,
    cooldown: 1.1,
    sound: 'whoosh',
    model: models.rocketLauncher,
    projectile: models.rocket,
    opts: { speed: 16, gravity: 0, radius: 2.4, embed: false },
  },

  // ---------------- Elemental ----------------
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    category: 'elemental',
    archetype: 'spray',
    icon: '🔥',
    price: 3500,
    damage: 3,
    type: 'fire',
    impulse: 0.5,
    cooldown: 0,
    sound: 'ignite',
    loop: 'flame',
    model: models.flamethrower,
    opts: { range: 4.5 },
  },
  {
    id: 'taser',
    name: 'Taser',
    category: 'elemental',
    archetype: 'spray',
    icon: '⚡',
    price: 2400,
    damage: 2.4,
    type: 'electric',
    impulse: 1,
    cooldown: 0,
    sound: 'zap',
    loop: 'electric',
    model: models.taser,
    opts: { range: 7 },
  },
  {
    id: 'freezeray',
    name: 'Freeze Ray',
    category: 'elemental',
    archetype: 'spray',
    icon: '❄️',
    price: 3000,
    damage: 2,
    type: 'cold',
    impulse: 0.3,
    cooldown: 0,
    sound: 'freeze',
    loop: 'freezeRay',
    model: models.freezeRay,
    opts: { range: 9 },
  },

  // ---------------- Drop ----------------
  {
    id: 'anvil',
    name: 'Anvil',
    category: 'drop',
    archetype: 'thrown',
    icon: '⚓',
    price: 4000,
    damage: 90,
    type: 'blunt',
    impulse: 0,
    cooldown: 1.2,
    sound: 'whoosh',
    hitSound: 'clang',
    words: ['CLANG!', 'SPLAT!', 'BONK!'],
    model: models.anvil,
    opts: { drop: true, mass: 90, shape: 'box', half: [0.25, 0.19, 0.11] },
  },
  {
    id: 'bowling',
    name: 'Bowling Ball',
    category: 'drop',
    archetype: 'thrown',
    icon: '🎳',
    price: 1000,
    damage: 30,
    type: 'blunt',
    impulse: 0,
    cooldown: 0.5,
    sound: 'whoosh',
    hitSound: 'thud',
    words: ['STRIKE!', 'BONK!'],
    model: models.bowlingBall,
    opts: { drop: true, mass: 7, shape: 'ball', half: [0.11, 0.11, 0.11] },
  },
];

export const CATEGORIES: Array<{ id: WeaponCategory | 'all'; label: string }> = [
  { id: 'all', label: 'All' },
  { id: 'blunt', label: 'Blunt' },
  { id: 'sharp', label: 'Sharp' },
  { id: 'gun', label: 'Guns' },
  { id: 'explosive', label: 'Boom' },
  { id: 'elemental', label: 'Elemental' },
  { id: 'drop', label: 'Drop' },
];

export function weaponById(id: string): WeaponDef {
  const w = WEAPONS.find((d) => d.id === id);
  if (!w) throw new Error(`Unknown weapon ${id}`);
  return w;
}
